volumes:
  bundle:
  play_bundle:

services:
  package:
    build: .
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_PORT=7700
      - BUNDLE_PATH=/vendor/bundle
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - bundle:/vendor/bundle
      - ./:/home/package
      # - ../meilisearch-ruby:/home/meilisearch-ruby

  playground:
    build:
      context: ./playground
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - BUNDLE_PATH=/vendor/bundle
    depends_on:
      - meilisearch
    working_dir: /home/app
    links:
      - meilisearch
    ports:
      - "3000:3000"
    volumes:
      - ./playground:/home/app
      - ./:/home/meilisearch-rails
      - play_bundle:/vendor/bundle

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
